server:
  address: 0.0.0.0
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

app:
  integrity:
    mode: real
    android:
      packageName: com.example.integritydemo
      certificateDigest: CHANGE_ME
    ios:
      bundleId: com.anson12666.integritydemomobile
      teamId: 538FVU496F
      appAttestEnvironment: development
